[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fprime-test-sequencer"
dynamic = ["version"]
dependencies = [
  "fprime-gds>=3.4.3"
]

[project.scripts]
fprime-test-sequencer = "fprime_test_sequencer.cli:main"
